pipeline {
    environment {
        team = "integration"                                                                   // Nombre necesario para crear infra en ./infra/team/productName
        namespace = "integration"                                                              // [Opcional] Nombre del namespace donde está desplegado 
        appalias = "sms-conector"                                                              // [Opcional] Alias con el que se desplegara
        productName = "sms-conector-v2"                                                        // Nombre que aloja el codigo fuente
        registryCredential = 'docker_hub'                                                      // credencial para acceso a hub
        dockerUser = "bancoganadero"                                                           // usuario con acceso
        dockerRepo = "${productName}"                                                          // Nombre del repositorio en el registro de contenedores
        dockerImageTAG = "${BUILD_ID}.${BUILD_TIMESTAMP_SHORT}.${BRANCH_NAME}"                 // Valor del TAG para la imagen
        sourceCodeURL = "git@gitlab.bg.com.bo:desarrollo/bga/integracion/${productName}.git"   // Git Codigo Fuente
        helmChartsURL = "https://BancoGanadero@dev.azure.com/BancoGanadero/BGA-Internal/_git/gitops"                // Git Helm Charts donde encontrar $chart y almacenar la infra
        dockerImage = ''                                                                       // Variable que representa las acciones de docker
        portName="http"                                                                        // Nombre del puerto que expone el contenedor
        portNumber=3000                                                                        // Numero del puerto a escuchar en el contenedor
        chart="simple-chart"                                                                   // Nombre del chart a utilizar para este proyecto
        language="javascript"                                                                  // Lenguaje de programación del proyecto
        stopCondition="--exit-code 1 --severity HIGH,CRITICAL"
        excludeIMG="base|build"
    }
    agent { node { label 'linux-builder' } }
    options { buildDiscarder logRotator( daysToKeepStr: '16',numToKeepStr: '10') }
    stages {
        stage('Cleanup Workspace') {
            steps {
                cleanWs()
                sh '''#!/bin/bash
                echo "Cleaned Up Workspace For ${productName} $(pwd)"
                '''
            }
        }
        stage('Code Checkout') {
            steps {
                script {
                    checkout([
                        $class: "GitSCM", 
                        branches: [[ name: "${BRANCH_NAME}" ]],
                        userRemoteConfigs: [[ credentialsId: "gitlab", url: "${sourceCodeURL}" ]]
                    ])
                }
            }
        }
        stage('Testing source code') {
            steps{
                sh """#!/bin/bash
                [ -f ./cicd/.trivyignore ] && { ignore="--ignorefile ./cicd/.trivyignore"; echo "Ignoring..."; cat ./cicd/.trivyignore; } || ignore=""
                echo " + Scanning from images..."
                for image in \$(find . -type f -iname "Dockerfile"|xargs grep -i "from "|awk '{print \$2}'|sort -u| grep -Evi "\${excludeIMG}"); do 
                   echo "  - Scann \$image"
                   docker run --rm aquasec/trivy:latest image \${stopCondition} \${ignore} --no-progress --scanners vuln \$image
                done
                echo " + Scanning for config"
                docker run --rm -v \$PWD:/to-scan aquasec/trivy:latest fs \${stopCondition} \${ignore} --scanners vuln,secret,config /to-scan --no-progress
                """
            }
        }
        stage('Sonarqube') {
            when { branch 'develop' }
            environment { scannerHome = tool 'sonarqube' }
            steps {
                withSonarQubeEnv( installationName: 'SonarQube-Prod', credentialsId: 'POC-Sonar') {
                    sh '''
                    ${scannerHome}/bin/sonar-scanner \
                    -Dsonar.projectKey=${team}-${productName} \
                    -Dsonar.projectName=${team}-${productName} \
                    -Dsonar.projectVersion=${BUILD_NUMBER} \
                    -Dsonar.language=${language}
                    '''
                }
                sleep 35
                timeout(time: 10, unit: 'MINUTES') { waitForQualityGate abortPipeline: true }
            }
        }
        stage('Build and Push Image') {
            when { anyOf { branch 'master'; branch 'develop'; branch 'staging'; branch 'release-*' } }
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                        try {    
                            sh '''#!/bin/bash
                            [ -f .env ] && cat ./cicd/env-${BRANCH_NAME%-*} > .env || echo "No tenemos .env definido"
                            '''                        
                            dockerImage = docker.build("${dockerUser}/${dockerRepo}:${dockerImageTAG}")
                            dockerImage.push()
                            dockerImage.push('latest')
                        } catch (error) {
                            sh "echo 'Creating new docker repository'"
                            sh "docker create repository --name ${dockerUser}/${dockerRepo}"
                            dockerImage.push()
                            dockerImage.push('latest')
                        }
                    }
                }
            }
        }
        stage('Remove Related Images') {
            when { anyOf { branch 'master'; branch 'develop'; branch 'staging'; branch 'release-*' } }
            steps{
                sh "docker rmi ${dockerUser}/${dockerRepo}:${dockerImageTAG}"
                sh "docker rmi ${dockerUser}/${dockerRepo}:latest"
            }
        }
        stage('Deploy with ArgoCD') {
            when { anyOf { branch 'master'; branch 'develop'; branch 'staging'; branch 'release-*' } }
            steps {
                sh "[ -f ./cicd/env-data.yaml ] && cp ./cicd/env-data.yaml /tmp/env-data-${productName}.yaml || echo 'No existe ./cicd/env-data.yaml'"
                git branch: "main", credentialsId: "azure-repo", url: "${helmChartsURL}"
                sh '''#!/bin/bash
                projectBranch="${BRANCH_NAME%-*}" bash ./devsecops-bga-tpls/bash-scripts/new-project.sh
                [ -f /tmp/env-data-${productName}.yaml ] && rm -fv /tmp/env-data-${productName}.yaml || echo "No existe /tmp/env-data-${productName}.yaml"
                '''
            }
        }
    }
}